import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Confirm from "@/components/confirm";

export const metadata: Metadata = {
  title: "招聘系统",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        {children}
        <Confirm />
        <Toaster />
      </body>
    </html>
  );
}
